name: Go

on: push

jobs:

  build:
    name: Build Go binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Windows Package
      run: env GOOS=windows GOARCH=amd64 go build -o bonusly -ldflags="-w -s" main.go && zip bonusly_win64.zip bonusly
    - name: Build MacOS Package
      run: env GOOS=darwin GOARCH=arm64 go build -o bonusly -ldflags="-w -s" main.go && tar -zcvf bonusly_macos_arm64.tar.gz bonusly
    - name: Build Ubuntu Package
      run: env GOOS=linux GOARCH=amd64 go build -o bonusly -ldflags="-w -s" main.go && tar -zvcf bonusly_linux_amd64.tar.gz bonusly
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Bonusly CLI
        files: |
          bonusly_win64.zip
          bonusly_macos_arm64.tar.gz
          bonusly_linux_amd64.tar.gz

