name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build Go binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: env GOOS=windows GOARCH=amd64 go build -o bonusly_win64.exe -ldflags="-w -s" main.go
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        prerelease: true
        name: Bonusly CLI
        files: bonusly_win64.exe


